### ISSUE TITLE
Can i use this if my program use internet

### ISSUE THREAD

**Issue by roberttestter** [wokwi/esp32-arduino-debug#1]
I wonder if I can debug my program if need internet connaction

**Comment by urish** [comment]
Hello, are you asking about the `esp32-arduino-debug` docker container?

Probably yes, but the purpose of the container is to be able to step through the esp-idf built-in component. It's probably not very relevant if you want to debug your own code.

**Comment by urish** [comment]
If you are asking about the Wokwi simulator, it's better to start a discussion on the online discord chat at https://wokwi.com/discord
